version: '3'
services:
  mysql:
    image: 'mysql:8.2.0'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_DATABASE: 'test'
  api:
    build: .
    container_name: api
    ports:
      - "3333:3333"
    volumes:
      - .:/app
      - /usr/src/app/node_modules
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    container_name: sqlite_db
    volumes:
      - sqlite_data:/data
    environment:
      - SQLITE_DATABASE=/data/database.sqlite

volumes:
  sqlite_data:
